- task: serve-html
  config:
    platform: linux
    image_resource:
      type: docker-image
      source: {repository: nginx, tag: stable}
    params:
      PORT: "8000"  
    inputs:
    - name: html-repo
  run:
    path: sh
    args:
    - -exc
    - |
      cp -r html-repo/* /usr/share/nginx/html/
      nginx -g 'daemon off;'
  ports:
  - "8000:8000"  
