resources:
- name: html-repo
  type: git
  source:
    uri: https://github.com/dharshan473/concourse-html.git
    branch: main

jobs:
- name: serve-html
  plan:
  - get: html-repo
    trigger: true
    params:
      depth: 1
      submodules: none
      destination: .
  - task: serve-html
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: latest}
      
      inputs:
      - name: html-repo
      run:
        path: sh
        args:
        - -exc
        - |
          ls -la
          pwd
          cd html-repo/
          ls -la
          apt-get update -y
          apt-get install nginx -y
          
          # Update NGINX configuration to listen on port 8081
          sed -i 's/80/8081/g' /etc/nginx/nginx.conf
          
          service nginx start
          
          # Copy HTML files to NGINX root directory
          cp -r index.html /var/www/html
          
          # Restart NGINX to apply changes
          service nginx restart
