resources:
- name: html-repo
  type: git
  source:
    uri: https://github.com/dharshan473/concourse-html.git
    branch: main

jobs:
- name: serve-html
  plan:
  - get: html-repo
    trigger: true
  - task: serve-html
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: nginx, tag: stable}
      params:
        PORT: "8000"
      inputs:
      - name: html-repo
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r html-repo/index.html /usr/share/nginx/html/
          nginx -g 'daemon off;'
