resources:
- name: html-repo
  type: git
  source:
    uri: https://github.com/dharshan473/concourse-html
    branch: main

jobs:
- name: serve-html
  plan:
  - get: html-repo
    trigger: true
  - task: serve-html
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: html-server, tag: latest}
      inputs:
      - name: html-repo
      run:
        path: sh
        args:
        - -exc
        - |
          cd html-repo
          python -m SimpleHTTPServer 8080
