resources:
- name: html-repo
  type: git
  source:
    uri: https://github.com/dharshan473/concourse-html.git
    branch: main

jobs:
- name: serve-html
  plan:
  - get: html-repo
    trigger: true
    params:
      depth: 1
      submodules: none
      destination: .
  - task: serve-html
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: latest}
      
      inputs:
      - name: html-repo
      run:
        path: sh
        args:
        - -exc
        - |
          ls -la
          cd html-repo

          ls -la
          apt-get update -y
          apt-get install nginx -y
          service nginx start
          service nginx status
          cd /var/www/html
          ls -la
          cp -rf index.html /var/www/html
          
          service nginx restart
